### ISSUE TITLE
gpg: Sorry, no terminal at all requested - can't get input

### ISSUE THREAD

**Issue by bjo81** [igagis/aptian#17]
gpg fails to sign repo when running in a script:

```
create dists/noble/Release
create dists/noble/Release.gpg
gpg: Sorry, no terminal at all requested - can't get input
ERROR: uncaught exception
  could not create gpg signature of Release file
```

**Comment by igagis** [comment]
Fixed in version `0.0.8`

**Comment by bjo81** [comment]
Unfortunately this did not fix it completely:

```
gpg: Sorry, we are in batchmode - can't get input
ERROR: uncaught exception
  could not create gpg signature of Release file
```

**Comment by igagis** [comment]
hm, strange... why does it want any input... 🤔

**Comment by igagis** [comment]
@bjo81 can ot be that you don't have a default gpg key set? so it wants to ask which gpg key to use?

**Comment by igagis** [comment]
@bjo81 or is your key password protected?

**Comment by bjo81** [comment]
In the used directory (given with `--dir`) an `aptian.conf` exists with `gpg{user@domain.net}` - so it should use that I think?

**Comment by bjo81** [comment]
> @bjo81 or is your key password protected?

Eh, you're right, it was password protected, yes.

**Comment by igagis** [comment]
yes, it should use the key indicated in the conf.
but it must not be password-protected, because aptian does not support that at the moment
