### ISSUE TITLE
pubkey.gpg no longer generated when rebuilding apt repository from scratch

### ISSUE THREAD

**Issue by ChristopherHX** [igagis/aptian#9]
I will take a look and see if I can contribute this

**Comment by igagis** [comment]
Is it actually needed? I just put the `pubkey.gpg` manually once to the repo base dir, so it could be downloaded and imported to APT on client side.

For example your `github-act-runner` repo the `pubkey.gpg` is here https://gagis.hopto.org/repo/chrishx/pubkey.gpg

But if you think it is handy to have this feature, I'd be happy to accept PR.

**Comment by igagis** [comment]
Well, it looks like generating `pubkey.gpg` should be just one `std::system()` call from C++ code, invoking the `gpg` command to export the public key. So, feel free to do it from your ci or by contributing a PR to `aptian`.  Whatever is easier for you.
